id = "templ"
name = "Templ"
version = "0.0.3"
schema_version = 1
authors = ["Mehmet Akif Duba <mail@makifdb.com>"]
description = "Templ language support for Zed"
repository = "https://github.com/makifdb/zed-templ"

[language_servers.templ]
name = "Templ Language Server"
language = "Templ"

[grammars.templ]
repository = "https://github.com/vrischmann/tree-sitter-templ"
commit = "71978ef587a9e4456333d62a5929949669af66fc"
